export default [
  {
  "doctorid": 16,
    "first_name": "Dr. Alok",
    "last_name": "Sharma",
    "address": "12A, MG Road",
    "city": "Mumbai",
    "state": "Maharashtra",
    "pincode": "400001",
    "phonenumber": "9898989898",
    "email": "aloksharma@example.com",
    "gender": "Male",
    "description": "Neurologist specializing in Parkinson's Disease and Movement Disorders.",
    "image": "path/to/image.jpg",
    "specialization": "Neurology",
    "education": "DM Neurology",
    "doctor_login_id": {
      "login_id": 31,
      "username": "alokneuro",
      "password": "doctor123",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": false
    }
  },
  {
    "doctorid": 17,
    "first_name": "Dr. Priya",
    "last_name": "Patel",
    "address": "21, Gandhi Nagar",
    "city": "Ahmedabad",
    "state": "Gujarat",
    "pincode": "380001",
    "phonenumber": "9876543210",
    "email": "priyapatel@example.com",
    "gender": "Female",
    "description": "Oncologist specializing in Cancer.",
    "image": "path/to/image.jpg",
    "specialization": "Oncology",
    "education": "MD Oncology",
    "doctor_login_id": {
      "login_id": 32,
      "username": "priyaonco",
      "password": "doctor456",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": true
    }
  },
  {
    "doctorid": 18,
    "first_name": "Dr. Rajesh",
    "last_name": "Singh",
    "address": "3, Indira Nagar",
    "city": "Delhi",
    "state": "Delhi",
    "pincode": "110001",
    "phonenumber": "9999999999",
    "email": "rajeshsingh@example.com",
    "gender": "Male",
    "description": "Orthopedic Surgeon specializing in Joint Replacement.",
    "image": "path/to/image.jpg",
    "specialization": "Orthopedics",
    "education": "MS Orthopedics",
    "doctor_login_id": {
      "login_id": 33,
      "username": "rajeshortho",
      "password": "doctor789",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": false
    }
  },
  {
    "doctorid": 19,
    "first_name": "Dr. Swati",
    "last_name": "Mishra",
    "address": "5, Nehru Nagar",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "pincode": "226001",
    "phonenumber": "9876543210",
    "email": "swatimishra@example.com",
    "gender": "Female",
    "description": "Dermatologist specializing in Skin Disorders and Cosmetic Dermatology.",
    "image": "path/to/image.jpg",
    "specialization": "Dermatology",
    "education": "MD Dermatology",
    "doctor_login_id": {
      "login_id": 34,
      "username": "swatiderm",
      "password": "doctor101",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": true
    }
  },
  {
    "doctorid": 20,
    "first_name": "Dr. Arjun",
    "last_name": "Kumar",
    "address": "8, Gandhi Road",
    "city": "Bangalore",
    "state": "Karnataka",
    "pincode": "560001",
    "phonenumber": "9898989898",
    "email": "arjunkumar@example.com",
    "gender": "Male",
    "description": "Pediatrician specializing in Child Development and Pediatric Neurology.",
    "image": "path/to/image.jpg",
    "specialization": "Pediatrics",
    "education": "MD Pediatrics",
    "doctor_login_id": {
      "login_id": 35,
      "username": "arjunped",
      "password": "doctor202",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": true
    }
  },
  {
    "doctorid": 3,
    "first_name": "Doca",
    "last_name": "Doa",
    "address": "Main",
    "city": "Pune",
    "state": "Maharashtra",
    "pincode": "411019",
    "phonenumber": "4544545445",
    "email": "doca21@gmail.com",
    "gender": "Male",
    "description": "Cardiologist",
    "image": null,
    "specialization": "surgon",
    "education": "MBBS",
    "doctor_login_id": {
      "login_id": 8,
      "username": "Doc1",
      "password": "Doc@12345",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": false
    }
  },
  {
    "doctorid": 4,
    "first_name": "Rajj",
    "last_name": "Pattell",
    "address": "Mainn",
    "city": "Pune",
    "state": "Maharashtra",
    "pincode": "411019",
    "phonenumber": "9780885445",
    "email": "pat1@gmail.com",
    "gender": "Male",
    "description": "Cardiologist",
    "image": null,
    "specialization": "surgon",
    "education": "Mbbs",
    "doctor_login_id": {
      "login_id": 9,
      "username": "Doc12",
      "password": "Doc@12345",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": false
    }
  },
  {
    "doctorid": 5,
    "first_name": "Rajjk",
    "last_name": "Pattelll",
    "address": "Mainn",
    "city": "Pune",
    "state": "Maharashtra",
    "pincode": "411019",
    "phonenumber": "9780885455",
    "email": "pa5t1@gmail.com",
    "gender": "Male",
    "description": "Cardiologist",
    "image": null,
    "specialization": "surgon",
    "education": "Mbbs",
    "doctor_login_id": {
      "login_id": 10,
      "username": "Doc122",
      "password": "Doc@12345",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": true
    }
  },
  {
    "doctorid": 7,
    "first_name": "Rajjkk",
    "last_name": "Pattellll",
    "address": "Mainn",
    "city": "Pune",
    "state": "Maharashtra",
    "pincode": "411019",
    "phonenumber": "9780885545",
    "email": "pa15sdt1@gmail.com",
    "gender": "Male",
    "description": "Cardiologist",
    "image": null,
    "specialization": "surgon",
    "education": "Mbbs",
    "doctor_login_id": {
      "login_id": 16,
      "username": "NotDoc22",
      "password": "Doc@12345",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": true
    }
  },
  {
    "doctorid": 9,
    "first_name": "Rajjkkk",
    "last_name": "Pattelllll",
    "address": "Mainn",
    "city": "Pune",
    "state": "Maharashtra",
    "pincode": "411019",
    "phonenumber": "4545554545",
    "email": "pa145sdt1@gmail.com",
    "gender": "Male",
    "description": "Cardiologist",
    "image": null,
    "specialization": "Surgon",
    "education": "MBBS",
    "doctor_login_id": {
      "login_id": 21,
      "username": "Doc1sddsss",
      "password": "Doc@12345",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": true
    }
  },
  {
    "doctorid": 11,
    "first_name": "Rajjkkks",
    "last_name": "Pattellllls",
    "address": "Mainn",
    "city": "Pune",
    "state": "Maharashtra",
    "pincode": "411019",
    "phonenumber": "4575554545",
    "email": "pa14s5sdt1@gmail.com",
    "gender": "Male",
    "description": "Cardiologist",
    "image": null,
    "specialization": "Surgon",
    "education": "MBBS",
    "doctor_login_id": {
      "login_id": 25,
      "username": "Doc1sddssssa",
      "password": "Doc@12345",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": true
    }
  },
  {
    "doctorid": 13,
    "first_name": "Sfdf",
    "last_name": "Padad",
    "address": "Mainnn",
    "city": "Pune",
    "state": "Maharashtra",
    "pincode": "411019",
    "phonenumber": "6565858284",
    "email": "akljdlakj@gmail.com",
    "gender": "Male",
    "description": "Cardiologist",
    "image": null,
    "specialization": "Surgon",
    "education": "MBBS",
    "doctor_login_id": {
      "login_id": 28,
      "username": "sdad",
      "password": "Sank@123",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": false
    }
  },
  {
    "doctorid": 14,
    "first_name": "Some",
    "last_name": "Pskjkls",
    "address": "Main",
    "city": "Pune",
    "state": "Maharashtra",
    "pincode": "455151",
    "phonenumber": "4548484848",
    "email": "Rsidja1@gmail.com",
    "gender": "Male",
    "description": "Cardiologist",
    "image": null,
    "specialization": "surgon",
    "education": "mbbs",
    "doctor_login_id": {
      "login_id": 29,
      "username": "Some",
      "password": "Doc@12345",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": true
    }
  },
  {
    "doctorid": 15,
    "first_name": "Abc",
    "last_name": "Abc",
    "address": "Main",
    "city": "Pune",
    "state": "Maharashtra",
    "pincode": "411019",
    "phonenumber": "9890000000",
    "email": "abc21@gmail.com",
    "gender": "Male",
    "description": "Cardiologist",
    "image": null,
    "specialization": "Surgon",
    "education": "MBBS",
    "doctor_login_id": {
      "login_id": 30,
      "username": "abc",
      "password": "Abc@1234",
      "role_id": { "roleid": 2, "rolename": "Doctor" },
      "id_approved": true
    }
  }
]
